//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iRentCronJob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class background
    {
        public int BackgroundID { get; set; }
        public Nullable<int> TenantID { get; set; }
        public string LastResidence { get; set; }
        public string LastLandlordName { get; set; }
        public string LastLandlordPhone { get; set; }
        public string PreviousResidence { get; set; }
        public string PreviousLandlordName { get; set; }
        public string PreviousLandlordPhone { get; set; }
        public string CurrentEmployer { get; set; }
        public string CurrentEmployerContact { get; set; }
        public string CurrentEmployerPhone { get; set; }
        public string CurrentSalary { get; set; }
        public string PreviousEmployer { get; set; }
        public string PreviousEmployerContact { get; set; }
        public string PreviousEmployerPhone { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> ApproveID { get; set; }
        public string ApproveComment { get; set; }
        public Nullable<int> HouseNumber { get; set; }
        public string StreetName { get; set; }
        public string Unit { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string HouseNumber2 { get; set; }
        public string StreetName2 { get; set; }
        public string City2 { get; set; }
        public string State2 { get; set; }
        public string Zip2 { get; set; }
        public string Vehicle1 { get; set; }
        public string Vehicle2 { get; set; }
        public string Vehicle3 { get; set; }
        public string Unit2 { get; set; }
        public string DriversLicense { get; set; }
        public string DLState { get; set; }
        public Nullable<System.DateTime> DesiredMoveInDate { get; set; }
        public string DesiredLeaseTerm { get; set; }
        public Nullable<decimal> DesiredRent { get; set; }
        public string FormerName { get; set; }
        public string CurrentOccupancyType { get; set; }
        public string LastLandlordEmail { get; set; }
        public Nullable<decimal> LastRentAmount { get; set; }
        public string LastMoveReason { get; set; }
        public Nullable<System.DateTime> LastMoveInDate { get; set; }
        public Nullable<bool> LastLandlordContact { get; set; }
        public string CurrentEmployeerStatus { get; set; }
        public string CurrentEmploymentType { get; set; }
        public Nullable<bool> CurrentSelfEmployment { get; set; }
        public string CurrentEmployeerEmail { get; set; }
        public string CurrentEmployeerAddress { get; set; }
        public string CurrentEmployeerPosition { get; set; }
        public Nullable<System.DateTime> CurrentEmployeerStartDate { get; set; }
        public string Background_PreviousEmploymentType { get; set; }
        public Nullable<bool> PreviousSelfEmployment { get; set; }
        public string PreviousEmployeerEmail { get; set; }
        public string PreviousEmployeerAddress { get; set; }
        public string PreviousEmployeerPosition { get; set; }
        public Nullable<decimal> PreviousEmployeerIncome { get; set; }
        public Nullable<System.DateTime> PreviousEmployeerStartDate { get; set; }
        public Nullable<System.DateTime> PreviousEmployeerEndDate { get; set; }
        public string OtherIncome { get; set; }
        public string Pets { get; set; }
        public string VehicleMake { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleYear { get; set; }
        public string VehicleColor { get; set; }
        public string VehicleLicensePlate { get; set; }
        public string VehicleLicensePlateState { get; set; }
        public string ProspectBank { get; set; }
        public string ProspectBankPhone { get; set; }
        public string ProspectBankAccount { get; set; }
        public string ReferenceName { get; set; }
        public string ReferenceRelationship { get; set; }
        public string ReferenceOccupation { get; set; }
        public string ReferenceAddress { get; set; }
        public string ReferencePhone { get; set; }
        public string ReferenceEmail { get; set; }
        public string EmergencyName { get; set; }
        public string EmergencyRelationship { get; set; }
        public string EmergencyPhone { get; set; }
        public string EmergencyEmail { get; set; }
        public string PreviousEmploymentType { get; set; }
        public Nullable<System.DateTime> CurrentAddressMoveIn { get; set; }
        public Nullable<System.DateTime> PreviousAddressMoveIn { get; set; }
        public Nullable<System.DateTime> PreviousAddressMoveOut { get; set; }
        public string CurrentCompanyName { get; set; }
        public string PreviousCompanyName { get; set; }
    }
}
