//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iRentCronJob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class checkregister
    {
        public int CheckRegisterID { get; set; }
        public int PropertyID { get; set; }
        public decimal Amount { get; set; }
        public int ExpenseTypeID { get; set; }
        public string Memo { get; set; }
        public System.DateTime CheckDate { get; set; }
        public int TransactionType { get; set; }
        public int Paid { get; set; }
        public int Reconciled { get; set; }
        public int VendorID { get; set; }
        public int Escrow { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public System.DateTime PaidDate { get; set; }
        public string InvoiceNumber { get; set; }
        public int SubmittedBy { get; set; }
    }
}
