//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iRentCronJob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_cc
    {
        public int Customer_CCID { get; set; }
        public int CustomerID { get; set; }
        public string CreditCard { get; set; }
        public string NameOnCard { get; set; }
        public string ExpirationMonth { get; set; }
        public string CCV { get; set; }
        public string PostalCode { get; set; }
        public string ExpirationYear { get; set; }
    }
}
