//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iRentCronJob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eviction
    {
        public int EvictionID { get; set; }
        public int TenantID { get; set; }
        public string ResponseID { get; set; }
        public string Name { get; set; }
        public string Reference { get; set; }
        public string Message { get; set; }
        public string Zone { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Middle { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Court { get; set; }
        public string Agency_State { get; set; }
        public string Agency_County { get; set; }
        public System.DateTime Filing_Date { get; set; }
        public string Case_No { get; set; }
        public string Plaintiff { get; set; }
        public string Notice_Type { get; set; }
        public string Judgement_Date { get; set; }
        public decimal Judgement_Amount { get; set; }
        public string Judgement { get; set; }
        public decimal Judgement_Sat_Amount { get; set; }
        public string Judgement_Rel_Date { get; set; }
        public string Dismissal_Date { get; set; }
        public string Plaintiff_Atty { get; set; }
        public string Plaintiff_Atty_Phone { get; set; }
        public System.DateTime SubmittedDate { get; set; }
        public int BackgroundCheckLogID { get; set; }
    }
}
