//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iRentCronJob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class expensetype
    {
        public int ExpenseTypeID { get; set; }
        public string ExpenseType1 { get; set; }
        public int CompanyID { get; set; }
        public int AccountTypeID { get; set; }
        public int Active { get; set; }
    }
}
