//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iRentCronJob.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyiRentEntities : DbContext
    {
        public MyiRentEntities()
            : base("name=MyiRentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<background> backgrounds { get; set; }
        public virtual DbSet<checkregister> checkregisters { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<customer_bank> customer_bank { get; set; }
        public virtual DbSet<customer_cc> customer_cc { get; set; }
        public virtual DbSet<eviction> evictions { get; set; }
        public virtual DbSet<expensetype> expensetypes { get; set; }
        public virtual DbSet<property> properties { get; set; }
        public virtual DbSet<stripe> stripes { get; set; }
        public virtual DbSet<stripe_customer> stripe_customer { get; set; }
        public virtual DbSet<stripepayoutdetail> stripepayoutdetails { get; set; }
        public virtual DbSet<stripepayout> stripepayouts { get; set; }
        public virtual DbSet<tenant> tenants { get; set; }
        public virtual DbSet<tenanttransaction> tenanttransactions { get; set; }
        public virtual DbSet<transactiontype> transactiontypes { get; set; }
        public virtual DbSet<unit> units { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<whitelable> whitelables { get; set; }
        public virtual DbSet<chargetype> chargetypes { get; set; }
        public virtual DbSet<collection> collections { get; set; }
        public virtual DbSet<frequency> frequencies { get; set; }
        public virtual DbSet<postmethod> postmethods { get; set; }
        public virtual DbSet<recurringbill> recurringbills { get; set; }
        public virtual DbSet<userlog> userlogs { get; set; }
        public virtual DbSet<vendor> vendors { get; set; }
        public virtual DbSet<whitelist> whitelists { get; set; }
        public virtual DbSet<userpropertymap> userpropertymaps { get; set; }
        public virtual DbSet<postvacancy> postvacancies { get; set; }
        public virtual DbSet<properties_exclude> properties_exclude { get; set; }
    }
}
