//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iRentCronJob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class postvacancy
    {
        public int PostVacancieID { get; set; }
        public int PropertyID { get; set; }
        public Nullable<int> AutoPostVacancies { get; set; }
        public Nullable<int> AutoRemoveNonVacancies { get; set; }
        public Nullable<int> UnitsUpdated { get; set; }
    }
}
