//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iRentCronJob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class properties_exclude
    {
        public int Properties_ExcludeID { get; set; }
        public int PropertyID { get; set; }
        public int AutoBill { get; set; }
        public int AutoBillNotify { get; set; }
    }
}
