//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iRentCronJob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stripepayoutdetail
    {
        public int StripePayoutDetailsID { get; set; }
        public int StripePayoutID { get; set; }
        public Nullable<decimal> AmountGross { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public Nullable<decimal> AmountNet { get; set; }
        public string Description { get; set; }
    }
}
