//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iRentCronJob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tenant
    {
        public int TenantID { get; set; }
        public string TenantFName { get; set; }
        public string TenantMName { get; set; }
        public string TenantLName { get; set; }
        public string TenantPhone { get; set; }
        public string TenantOtherPhone { get; set; }
        public string TenantEmail { get; set; }
        public string SSN { get; set; }
        public string ProspectComments { get; set; }
        public Nullable<System.DateTime> ProspectStartDate { get; set; }
        public Nullable<int> UnitTypeID { get; set; }
        public Nullable<int> Prospect { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> PropertyID { get; set; }
        public Nullable<System.DateTime> LeaseStartDate { get; set; }
        public Nullable<System.DateTime> LeaseEndDate { get; set; }
        public Nullable<System.DateTime> MoveInDate { get; set; }
        public Nullable<System.DateTime> MoveOutDate { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<decimal> RentalAmount { get; set; }
        public Nullable<decimal> HousingAmount { get; set; }
        public Nullable<decimal> SecurityDeposit { get; set; }
        public Nullable<decimal> PetRent { get; set; }
        public Nullable<decimal> TVCharge { get; set; }
        public Nullable<decimal> UtilityCharge { get; set; }
        public Nullable<int> Collections { get; set; }
        public Nullable<int> WhiteList { get; set; }
        public Nullable<int> EvictionFiled { get; set; }
        public Nullable<System.DateTime> EvictionFiledDate { get; set; }
        public Nullable<int> LeaseUpload { get; set; }
        public Nullable<int> LeaseAudit { get; set; }
        public Nullable<int> CellPhoneProviderID { get; set; }
        public Nullable<int> LeadSourceID { get; set; }
        public string OnLease { get; set; }
        public Nullable<decimal> StorageCharge { get; set; }
        public Nullable<decimal> ParkingCharge { get; set; }
        public decimal ConcessionAmount { get; set; }
        public string ConcessionReason { get; set; }
        public Nullable<int> NoticeGiven { get; set; }
        public string DelinquencyComments { get; set; }
        public Nullable<int> MTM { get; set; }
        public Nullable<int> MoveOutReasonID { get; set; }
        public Nullable<decimal> HOAFee { get; set; }
        public string TenantDescriptionText { get; set; }
        public Nullable<System.DateTime> LastInitialLateFee { get; set; }
    }
}
