//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iRentCronJob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tenanttransaction
    {
        public int TenantTransactionID { get; set; }
        public int ChargeTypeID { get; set; }
        public int TenantID { get; set; }
        public int TransactionTypeID { get; set; }
        public decimal TransactionAmount { get; set; }
        public string Comment { get; set; }
        public System.DateTime TenantTransactionDate { get; set; }
        public int PaymentTypeID { get; set; }
        public int CheckRegisterID { get; set; }
        public int SubmittedBy { get; set; }
        public string CheckNumber { get; set; }
        public int DepositSourceID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> Allocated { get; set; }
        public Nullable<decimal> AmountAllocated { get; set; }
    }
}
