//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iRentCronJob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userlog
    {
        public int UserLogID { get; set; }
        public int LastPropertyID { get; set; }
        public System.DateTime LoginDate { get; set; }
        public System.DateTime LogoutDate { get; set; }
        public int UserID { get; set; }
    }
}
