//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iRentCronJob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int UserID { get; set; }
        public string UserFName { get; set; }
        public string UserLName { get; set; }
        public string UserEmail { get; set; }
        public string UserPhone { get; set; }
        public int CellPhoneProviderID { get; set; }
        public string UserPW { get; set; }
        public System.DateTime UserStartDate { get; set; }
        public int CompanyID { get; set; }
        public int SecurityLevelID { get; set; }
        public int Active { get; set; }
        public string SignatureName { get; set; }
        public string SignatureFont { get; set; }
    }
}
