//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iRentCronJob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class whitelable
    {
        public int WhiteLableID { get; set; }
        public string CompanyName { get; set; }
        public string Logo { get; set; }
        public string BannerColor { get; set; }
        public string LeftMarginColor { get; set; }
        public string WelcomeColor { get; set; }
        public string Style { get; set; }
        public string Logout { get; set; }
        public string PriceImage { get; set; }
        public string Promo1 { get; set; }
    }
}
