//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iRentCronJob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class whitelist
    {
        public int WhiteListID { get; set; }
        public int PropertyID { get; set; }
        public int UserID { get; set; }
        public System.DateTime MoveOutDate { get; set; }
        public int TenantID { get; set; }
        public string TenantEmail { get; set; }
        public string TenantPhone { get; set; }
        public string FAddress { get; set; }
        public string FCity { get; set; }
        public string FState { get; set; }
        public string FZip { get; set; }
        public int Whitelist1 { get; set; }
        public int Collections { get; set; }
        public System.DateTime SubmitDate { get; set; }
        public int RentAgain { get; set; }
        public string WhiteListComments { get; set; }
    }
}
